[package]
name = "telid"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.3.0"
chumsky = "0.9.2"
ordered-float = "3.7.0"
scoped_stack = "1.1.0"
strum = "0.25.0"
strum_macros = "0.25.2"
