let fn fizzbuzz n =
  if == % n 15 0
    'FizzBuzz'
  else if == % n 3 0
    'Fizz'
  else if == % n 5 0
    'Buzz'
  else
    n;

println(fizzbuzz(1));
println(fizzbuzz(2));
println(fizzbuzz(3));
println(fizzbuzz(4));
println(fizzbuzz(5));
println(fizzbuzz(6));
println(fizzbuzz(7));
println(fizzbuzz(8));
println(fizzbuzz(9));
println(fizzbuzz(10));
println(fizzbuzz(11));
println(fizzbuzz(12));
println(fizzbuzz(13));
println(fizzbuzz(14));
println(fizzbuzz(15));
